---

- name: check file
  stat:
    path: /var/www/src/public/index.php
  register: file

- name: install laravel
  shell: |
    composer create-project --prefer-dist laravel/laravel /var/www/src
  when: not file.stat.exists

- name: set permission
  shell: "{{ item }}"
  with_items:
    - chmod 755 -R /var/www/src
    - chmod 777 -R /var/www/src/storage
    - chmod 777 -R /var/www/src/bootstrap/cache
