
- name: install php7.3
  command: "amazon-linux-extras install php7.3 -y"

- name: install php 7.3 modules
  yum:
    name:
      - php
      - php-devel
      - php-fpm
      - php-gd
      - php-mbstring
      - php-mcrypt
      - php-mysqlnd
      - php-pdo
      - php-xml
      - php-zip

- name: setting php-fpm
  replace:
    path: /etc/php-fpm.d/www.conf
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - { regexp: "^user = apache", replace: "user = nginx" }
    - { regexp: "^group = apache", replace: "group = nginx" }
    - { regexp: "^listen = /run/php-fpm/www.sock", replace: "listen = /run/php-fpm/php-fpm.sock" }
    - { regexp: "^;listen.owner = nobody", replace: "listen.owner = nginx" }
    - { regexp: "^;listen.group = nobody", replace: "listen.group = nginx" }
    - { regexp: "^;listen.mode = 0660", replace: "listen.mode = 0660" }

- name: install composer
  command: "{{ item }}"
  with_items:
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - mv composer.phar /usr/bin/composer
    - composer config -g repos.packagist composer https://packagist.jp
    - composer global require hirak/prestissimo

- name: start php-fpm
  service:
    name: php-fpm
    state: started
    enabled: yes

